# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-29 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 16, 0, 42, 625219)),
        ),
        migrations.AddField(
            model_name='student',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 16, 0, 42, 625219)),
        ),
    ]
