# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-29 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0003_auto_20180629_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
