# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-29 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0005_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
