# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-29 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0006_auto_20180629_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 6, 29, 16, 55, 3, 343930)),
        ),
    ]
