# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-29 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0007_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=None),
        ),
    ]
